#! /usr/bin/bash -ex
../../sensorgnome-build/docker/sensorgnome-armv7-rpi-bullseye ./gen_package.sh
PI=pi@sg-eth
scp sg-wifi-button.deb $PI:
ssh $PI sudo apt remove -y sg-wifi-button
ssh $PI sudo apt install -y ./sg-wifi-button.deb
ssh $PI sudo systemctl daemon-reload
ssh $PI sudo systemctl restart wifi-init
ssh $PI sudo systemctl restart gestures
ssh $PI sudo wpa_cli -i wlan0 reconfigure
