#! /usr/bin/bash -e
echo "Running sg-web-portal postinst in $(pwd)"
WP=/opt/sensorgnome/web-portal # would be nice to derive that from some env var...

# install CaddyFile
cp $WP/Caddyfile /etc/caddy

# enable and start/restart gestures and wifi_init units
for U in sg-web-portal; do
    # code from debhelper's postinst-systemd-enable template
    if [ "$1" = "configure" ] || [ "$1" = "abort-upgrade" ] || [ "$1" = "abort-deconfigure" ] || [ "$1" = "abort-remove" ] ; then
        # This will only remove masks created by d-s-h on package removal.
        deb-systemd-helper unmask $U >/dev/null || true

        # was-enabled defaults to true, so new installations run enable.
        if deb-systemd-helper --quiet was-enabled $U; then
            # Enables the unit on first installation, creates new
            # symlinks on upgrades if the unit file has changed.
            deb-systemd-helper enable $U.service || true
        else
            # Update the statefile to add new symlinks (if any), which need to be
            # cleaned up on purge. Also remove old symlinks.
            deb-systemd-helper update-state $U >/dev/null || true
        fi
    fi
done
