#! /usr/bin/bash -e
echo "Running sg-sixfab postinst"
MISC=/opt/sixfab
cd $MISC
bash -e ./postinstall.sh

# restart service if running
# U=sixfab-core
# if systemctl is-active --quiet $U.service; then
#     echo "Restarting $U.service"
#     systemctl restart $U.service
# fi

systemctl stop sixfab-core.service || true
systemctl disable sixfab-core.service || true
rm -f /etc/udev/rules.d/30-sixfab.rules
