#! /usr/bin/bash -ex
echo "Running sg-cellular postinst in $(pwd)"
SRC=/opt/sensorgnome/cellular # would be nice to derive that from some env var...

systemctl daemon-reload
deb-systemd-helper enable check-modem.timer
if systemctl is-active --quiet check-modem.timer; then
  systemctl restart check-modem.timer
fi

echo "Done"
