#! /bin/bash -ex
../../sensorgnome-build/docker/sensorgnome-armv7-rpi-bullseye ./gen_package.sh
PI=pi@sg-eth
scp sg-gps-clock.deb $PI:
ssh $PI sudo apt remove -y sg-gps-clock || true
ssh $PI sudo apt install -y ./sg-gps-clock.deb
ssh $PI sudo systemctl daemon-reload
ssh $PI sudo systemctl restart chrony
ssh $PI sudo systemctl restart sg-gps-link
