#! /bin/bash -ex
../../sensorgnome-build/docker/sensorgnome-armv7-rpi-buster ./gen_package.sh
PI=pi@sg-eth
scp sg-ssh-tunnel.deb $PI:
ssh $PI sudo apt remove -y sg-ssh-tunnel || true
ssh $PI sudo apt install -y ./sg-ssh-tunnel.deb
ssh $PI sudo systemctl daemon-reload
ssh $PI sudo systemctl restart sg-register ssh-tunnel
