#! /bin/bash -ex
./gen-package.sh
PI=pi@${1:-sgpi.local}
PKG=sg-udev-usb_$(date +%Y.%j)_armhf.deb
scp ../packages/$PKG $PI:
ssh $PI sudo apt remove -y sg-udev-usb || true
ssh $PI sudo apt install -y ./$PKG
ssh $PI sudo systemctl daemon-reload
ssh $PI sudo systemctl restart sg-usb-init
