#! /bin/bash -ex
../../sensorgnome-build/docker/sensorgnome-armv7-rpi-buster ./gen_package.sh
PI=pi@sg-eth
scp sg-udev-usb.deb $PI:
ssh $PI sudo apt remove -y sg-udev-usb || true
ssh $PI sudo apt install -y ./sg-udev-usb.deb
ssh $PI sudo systemctl daemon-reload
ssh $PI sudo systemctl restart sg-usb-init
