#! /usr/bin/bash -e
echo "Running sg-hub-agent postinst in $(pwd)"
MISC=/opt/sensorgnome/hub-agent # would be nice to derive that from some env var...

# sg-boot owns /etc/telegraf.conf due to a boo-boo
[[ -f /etc/telegraf/telegraf.new ]] && mv /etc/telegraf/telegraf.new /etc/telegraf/telegraf.conf

# dir for hub-agent state
mkdir -p /var/lib/sensorgnome

# enable and start/restart hub-agent units
for U in sg-hub-agent; do
    # code from debhelper's postinst-systemd-enable template
    if [ "$1" = "configure" ] || [ "$1" = "abort-upgrade" ] || [ "$1" = "abort-deconfigure" ] || [ "$1" = "abort-remove" ] ; then
        # This will only remove masks created by d-s-h on package removal.
        deb-systemd-helper unmask $U >/dev/null || true

        # was-enabled defaults to true, so new installations run enable.
        if deb-systemd-helper --quiet was-enabled $U; then
            # Enables the unit on first installation, creates new
            # symlinks on upgrades if the unit file has changed.
            deb-systemd-helper enable $U.service || true
        else
            # Update the statefile to add new symlinks (if any), which need to be
            # cleaned up on purge. Also remove old symlinks.
            deb-systemd-helper update-state $U >/dev/null || true
        fi
    fi

    # Restart service, if it is running
    systemctl daemon-reload
    if systemctl is-active --quiet $U.service; then
        echo "Restarting $U.service"
        systemctl restart $U.service
    fi
done
