#! /usr/bin/bash -e
echo "Running sg-upgrader postinst"
SOURCES=/opt/sensorgnome/upgrader/sources
cd $SOURCES
shopt -s nullglob

# copy changed sources.list files to /etc/apt/sources.list.d
TGT=/etc/apt/sources.list.d
for s in *.list; do
    if ! cmp -s "$s" "$TGT/$s"; then
        echo "Updating $TGT/$s"
        cp "$s" "$TGT/$s"
        touch /run/double-update # cause check script to re-run apt update
    fi
done

# copy changed key files to /usr/share/keyrings
TGT=/usr/share/keyrings
for s in *.gpg; do
    if ! cmp -s "$s" "$TGT/$s"; then
        echo "Updating $TGT/$s"
        cp "$s" "$TGT/$s"
        touch /run/double-update # cause check script to re-run apt update
    fi
done

# run bail-out scripts
for s in bail-me-out/*.sh; do
    echo "Running $s"
    $s
done

# big hack to upgrade from old versions that didn't have this postinst script
if ! [[ -f /opt/sensorgnome/upgrader/has-double ]]; then
    echo "*** Spawning double-upgrade"
    TERM=dumb systemd-run --service-type=oneshot --description="sg-double-upgrade" \
        --no-block --collect \
        -E DEBIAN_FRONTEND=noninteractive \
        /bin/bash -ex -c /opt/sensorgnome/upgrader/do-double.sh
fi
