#! /usr/bin/bash -e
echo "Running sg-wifi-button postinst in $(pwd)"
MISC=/opt/sensorgnome/wifi-button/misc # would be nice to derive that from some env var...

# enable device tree overlay that turns on the button GPIO pull-up
cp $MISC/gpio_pull.dtbo /boot/overlays # can't let dpkg do that 'cause chmod doesn't work on fat32
# enabling is now done dynamically if HAT detected
# if ( ! grep -q dtoverlay=gpio_pull /boot/config.txt ); then
#   printf "#load overlay for SG LED-pushbutton switch\ndtoverlay=gpio_pull\n" >> /boot/config.txt
# fi

# install network.txt if not there
#[[ -f /etc/sensorgnome/network.txt ]] || cp $MISC/network.txt /etc/sensorgnome

# enable and start/restart gestures and wifi_init units
for U in wifi-init gestures; do
    # code from debhelper's postinst-systemd-enable template
    if [ "$1" = "configure" ] || [ "$1" = "abort-upgrade" ] || [ "$1" = "abort-deconfigure" ] || [ "$1" = "abort-remove" ] ; then
        # This will only remove masks created by d-s-h on package removal.
        deb-systemd-helper unmask $U >/dev/null || true

        # was-enabled defaults to true, so new installations run enable.
        if deb-systemd-helper --quiet was-enabled $U; then
            # Enables the unit on first installation, creates new
            # symlinks on upgrades if the unit file has changed.
            deb-systemd-helper enable $U.service || true
        else
            # Update the statefile to add new symlinks (if any), which need to be
            # cleaned up on purge. Also remove old symlinks.
            deb-systemd-helper update-state $U >/dev/null || true
        fi
    fi
done

# disable hostapd and dnsmasq auto-startup, we want to start them ourselves when appropriate
deb-systemd-helper disable hostapd.service
deb-systemd-helper disable dnsmasq.service
#sed -i 's/^dnsmasq/#dnsmasq/' /etc/resolvconf.conf
# prevent dnsmasq from becoming the system resolver:
egrep -q DNSMASQ_EXCEPT /etc/default/dnsmasq || echo DNSMASQ_EXCEPT=lo >> /etc/default/dnsmasq

# disable dhcp client on AP interface
if ! egrep -q ap0 /etc/dhcpcd.conf; then \
	  cat $MISC/etc-dhcpcd.conf >>/etc/dhcpcd.conf; \
fi
