name: Build packages

on: [push]

permissions:
  id-token: write
  contents: write

jobs:
  build-deb:
    uses: tve/sensorgnome-build/.github/workflows/generate-deb.yml@pimod
    with:
      command: ./gen-all-packages.sh
    secrets:
      GPG_PRIVATE_KEY: ${{ secrets.GPG_PRIVATE_KEY }}
      GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}
