name: Build packages

on: [push]

env:
  S3_PATH: motus-builds/${{github.repository}}
  S3_REGION: us-east-2

permissions:
  id-token: write
  contents: write

jobs:
  build-all:
    # run on x64 which has the debian tools, the one thing this may not do is build the
    # device tree overlay in the wifi-button subsystem, but the binary is checked-in and
    # so far never needs to be rebuilt. Revisit this if we ever need to build the dtbo. 
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          path: .
      - run: pwd
      - run: ls
      - run: ls ..
      - run: echo "GIT_DESC=$(git describe --tags --dirty --always)" >>$GITHUB_ENV
      - name: Generate .deb packages
        run: ./gen-all-packages.sh
        shell: bash
      - run: ls -ls packages
      - uses: actions/upload-artifact@v2
        with:
          name: deb-packages
          path: packages
      - name: Configure AWS Credentials
        # See https://docs.github.com/en/actions/deployment/security-hardening-your-deployments/configuring-openid-connect-in-amazon-web-services
        uses: aws-actions/configure-aws-credentials@master
        with:
          role-to-assume: arn:aws:iam::635201719205:role/Github-actions-motus
          role-session-name: GithubActionsMotus
          aws-region: ${{ env.S3_REGION }}
      - name: Upload .debs to AWS S3 repo
        run: |
          aws s3 sync packages s3://${{env.S3_PATH}}/$GIT_DESC/
      - name: Link to packages on S3
        run: |
          echo "https://${{env.S3_PATH}}/$GIT_DESC/"
          echo "::notice title=Packages::https://${{env.S3_PATH}}/$GIT_DESC/"
